---
parameters:
  env(GRPC_SERVER_ADDR): ''

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Client\Command\:
    resource: '../../src/Client/Command'
    tags: ['controller.service_arguments']

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\Client\:
    resource: '../../src/Client'
    exclude: '../../src/Client/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Client\Grpc\GrpcClientFactory:
    arguments:
      - '%env(resolve:GRPC_SERVER_ADDR)%'
